# Generated by Django 4.0.5 on 2022-06-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbd', '0002_rename_coach_team_coach_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('BO', 'Black Orc'), ('CC', 'Chaos Chosen'), ('CR', 'Chaos Renegades'), ('DE', 'Dark Elf'), ('DW', 'Dwarf'), ('EU', 'Elven Union'), ('GM', 'Goblin'), ('HA', 'Halfling'), ('HM', 'Human'), ('IN', 'Imperial Nobility'), ('LZ', 'Lizardmen'), ('NH', 'Necromantic Horror'), ('NU', 'Nurgle'), ('OG', 'Ogre'), ('OW', 'Old World ALliance'), ('OR', 'Orc'), ('SU', 'Shambling Undead'), ('SK', 'Skaven'), ('SN', 'Snolting'), ('UD', 'Underworld Denizens'), ('WE', 'Wood Elf')], default='BO', max_length=2),
        ),
    ]
