# Generated by Django 4.0.5 on 2022-06-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbd', '0003_team_team_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['last_name', 'first_name'], name='bbd_player_last_na_b4f34c_idx'),
        ),
    ]
